
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - port: 8500
    targetPort: 80
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      nodeSelector:
         beta.kubernetes.io/os: linux
      containers:
      - name: demo

        image: docker.pkg.github.com/ahmedappout08/dockerwebapp/demo:master
        envFrom:
        - secretRef:
            name: demo-secrets

        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred

