
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      nodeSelector:
         beta.kubernetes.io/os: linux
      containers:
      - name: demo
        image: docker.pkg.github.com/ahmedappout08/dockerwebapp/image:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
