apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  selector:
    matchLabels:
      app: test-image
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-image
        tier: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - production
      containers:
      - image: TEST_IMAGE_NAME
        name: test-image
        ports:
        - containerPort: 8500
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      imagePullSecrets:
        - name: regcred  
      tolerations:
        - key: "production"
          operator: "Equal"
          value: "LG"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: test-image
    tier: frontend
